Beloop\Component\Course\Entity\Course:
    type: entity
    repositoryClass: Beloop\Component\Course\Repository\CourseRepository
    table: course

    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        name:
            column: name
            type: string
            length: 255
            nullable: false
        code:
            column: code
            type: string
            length: 255
            unique: true
            nullable: false
        description:
            column: description
            type: text
            nullable: false
        imageName:
            column: image_name
            type: string
            length: 255
            nullable: true
        demo:
            column: demo
            type: boolean
            nullable: false
            options:
                default: false
        enabled:
            column: enabled
            type: boolean
            nullable: false
        createdAt:
            column: created_at
            type: datetime
            nullable: false
        updatedAt:
            column: updated_at
            type: datetime
            nullable: false

    manyToOne:
        language:
            targetEntity: Beloop\Component\Language\Entity\Language
            joinColumn:
                name: language_iso
                referencedColumnName: iso

    oneToMany:
        lessons:
            targetEntity: Beloop\Component\Course\Entity\Lesson
            mappedBy: course
            cascade: [ persist ]
        enrollments:
            targetEntity: Beloop\Component\Course\Entity\CourseEnrolledUser
            mappedBy: course
            cascade: [ persist ]

    lifecycleCallbacks:
        preUpdate: [loadUpdateAt]
        prePersist: [loadUpdateAt]
