Beloop\Component\Course\Entity\Abstracts\ExternalModule:
    type: entity
    inheritanceType: SINGLE_TABLE
    table: external_module
    discriminatorColumn:
        name: type
        type: string

    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        url:
            column: url
            type: string
            length: 255
            nullable: false

    lifecycleCallbacks:
        preUpdate: [loadUpdateAt]
        prePersist: [loadUpdateAt]
