services:

    #
    # Factories
    #

    #
    # Factory for entity course
    #
    beloop.factory.course:
        class: Beloop\Component\Course\Factory\CourseFactory
        arguments:
            - '@beloop.factory.language'
        calls:
            - [setEntityNamespace, ["%beloop.entity.course.class%"]]

    beloop.factory.lesson:
        class: Beloop\Component\Course\Factory\LessonFactory
        calls:
            - [setEntityNamespace, ["%beloop.entity.lesson.class%"]]

    beloop.factory.page:
        class: Beloop\Component\Course\Factory\PageFactory
        calls:
            - [setEntityNamespace, ["%beloop.entity.page.class%"]]