services:

    #
    # Object Managers
    #
    beloop.object_manager.course:
        parent: beloop.abstract_manager
        arguments:
            - %beloop.entity.course.class%

    beloop.object_manager.lesson:
        parent: beloop.abstract_manager
        arguments:
            - %beloop.entity.lesson.class%