services:

    #
    # Repositories
    #

    #
    # Repository for entity course
    #
    beloop.repository.course:
        parent: beloop.abstract_repository
        arguments:
            - %beloop.entity.course.class%

    beloop.repository.lesson:
        parent: beloop.abstract_repository
        arguments:
            - %beloop.entity.lesson.class%

    beloop.repository.page:
        parent: beloop.abstract_repository
        arguments:
            - %beloop.entity.page.class%