services:

    #
    # User enrollment
    #
    beloop.user_enrollment:
        class: Beloop\Component\Course\Services\UserEnrollment
        arguments:
            - '@beloop.csv_transformer.user'
            - '@beloop.manager.user'
            - '@beloop.director.course'
            - '@beloop.director.user'
            - '@beloop.factory.course_enrolled_user'
